config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  resources :exams
  resources :payments
  resources :reports
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new
    @exam = Exam.new
end

def create
    exam = Exam.new(exam_params)
    exam.save
    flash[:notice] = "exam has been created"
    redirect_to exams_path
end

def index
    @exam = Exam.all
end

def edit
    @exam = Exam.find(params[:id])
end

def update
    @exam = Exam.find(params[:id])
    @exam.update(exam_params)
    flash[:notice] = "exam has been updated"
    redirect_to exam_path(@exam)
end

def destroy
  @exam = Exam.find(params[:id])
  @exam.destroy
  redirect_to exams_path
  flash[:notice] = "Berhasil dihapus"
end

  def show
    @exam = Exam.find(params[:id])
  end
  

end

  private
  def exam_params
    params.require(:exam).permit(
      :title, :mapel, :duration, :nilai, :status, :level, :student_id
    )
  end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
end

def create
    payment = Payment.new(payment_params)
    payment.save
    flash[:notice] = "payment has been created"
    redirect_to payments_path
end

def index
    @payment = Payment.all
end

def edit
    @payment = Payment.find(params[:id])
end

def update
    @payment = Payment.find(params[:id])
    @payment.update(payment_params)
    flash[:notice] = "payment has been updated"
    redirect_to payment_path(@payment)
end

def destroy
  @payment = Payment.find(params[:id])
  @payment.destroy
  flash[:notice] = "Berhasil dihapus"
  redirect_to payments_path
  
end

def show
    @payment = Payment.find(params[:id])
end
  

end

  private
  def payment_params
    params.require(:payment).permit(
      :id_transtaction, :status, :upload
    )
  end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new
    @report = Report.new
end

def create
    report = Report.new(report_params)
    report.save
    flash[:notice] = "report has been created"
    redirect_to reports_path
end

def index
    @report = Report.all
end

def edit
    @report = Report.find(params[:id])
end

def update
    @report = Report.find(params[:id])
    @report.update(report_params)
    flash[:notice] = "report has been updated"
    redirect_to report_path(@report)
end

def destroy
  @report = Report.find(params[:id])
  @report.destroy
  redirect_to reports_path
  flash[:notice] = "Berhasil dihapus"
end

  def show
    @report = Report.find(params[:id])
  end
  

end

  private
  def report_params
    params.require(:report).permit(
      :title, :hasil, :mapel, :teacher_id, :student_id, :date
    )
  end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
end

def create
    student = Student.new(student_params)
    student.save
    flash[:notice] = "Student has been created"
    redirect_to students_path
end

def index
    @student = Student.all
end

def edit
    @student = Student.find(params[:id])
end

def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    flash[:notice] = "Student has been updated"
    redirect_to student_path(@student)
end

def destroy
  @student = Student.find(params[:id])
  @student.destroy
  redirect_to students_path
  flash[:notice] = "Berhasil dihapus"
end

  def show
    @student = Student.find(params[:id])
  end
  

end

  private
  def student_params
    params.require(:student).permit(:name, :username, :age, :kelas, :address, :city, :nik)
  end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @teacher = Teacher.new
end

def create
    teacher = Teacher.new(teacher_params)
    teacher.save
    flash[:notice] = "teacher has been created"
    redirect_to teachers_path
end

def index
    @teacher = Teacher.all
end

def edit
    @teacher = Teacher.find(params[:id])
end

def update
    @teacher = Teacher.find(params[:id])
    @teacher.update(teacher_params)
    flash[:notice] = "teacher has been updated"
    redirect_to teacher_path(@teacher)
end

def destroy
  @teacher = Teacher.find(params[:id])
  @teacher.destroy
  redirect_to teachers_path
  flash[:notice] = "Berhasil dihapus"
end

  def show
    @teacher = Teacher.find(params[:id])
  end
  

end

  private
  def teacher_params
    params.require(:teacher).permit(
      :nik, :name, :age, :kelas, :mapel
    )
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
<div class="row">
<div class="col-sm-5">
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title, class:"form-control"%> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel, class:"form-control" %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration, class:"form-control" %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai, class:"form-control" %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status, class:"form-control" %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level, class:"form-control" %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id, class:"form-control" %> </br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/exams/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
<table class="table">
    <tr>
        <th>title</th>
        <th>Mapel</th>
        <th>Action</th>
    </tr>
    <% @exam.each do |s|%>
    <tr>
        <td><%= s.title %></td>
        <td><%= s.mapel %></td>
        <td><%= link_to 'Detail', exam_path(s), class:"btn btn-info" %> <%= link_to 'Edit', edit_exam_path(s), class:"btn btn-warning" %>
        <%= link_to 'Delete', s , class:"btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
</table>
<%= link_to 'New Teacher', new_exam_path(), class:"btn btn-success" %>

app/views/exams/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="row">
<div class="col-sm-5">
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>
</div>

app/views/exams/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class= "container">
<div class= "row">
<div class= "col-sm-5">
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
Title : <%= @exam.title %> </br>
Mapel : <%= @exam.mapel %> </br>
Duration : <%= @exam.duration %> </br>
Nilai : <%= @exam.nilai %> </br>
Status : <%= @exam.status %> </br>
Level : <%= @exam.level %> </br>
StudentId : <%= @exam.student_id %> </br>
<%= link_to 'Home', exams_path(), class:"btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LivecodeKejarid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="form-group">
<div class="container">
  <div class="row">
    <div class="col-sm-5">
<%= form_for(@payment) do |f| %>
    <%= f.label :id_transtaction %> </br>
    <%= f.text_field :id_transtaction , class:"form-control"%> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status, class:"form-control"%> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload, class:"form-control" %> </br>
    <%= f.submit "Save" , class:"btn btn-success"%>
<% end %>
</div>
</div>
</div>
</div>

app/views/payments/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %>

</br>

<table class="table">
    <tr>
        <th>ID-Transsaction</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    <% @payment.each do |s|%>
    <tr>
        <td><%= s.id_transtaction %></td>
        <td><%= s.status %></td>
        <td><%= link_to 'Detail', payment_path(s), class:"btn btn-info" %> <%= link_to 'Edit', edit_payment_path(s), class:"btn btn-warning" %>
        <%= link_to 'Delete', s , class:"btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
</table>

&nbsp; <%= link_to "New", new_payment_path(), class:"btn btn-success" %>

app/views/payments/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="form-group">
<div class="container">
  <div class="row">
    <div class="col-sm-5">
<%= form_for(@payment) do |f| %>
    <%= f.label :id_transtaction %> </br>
    <%= f.text_field :id_transtaction , class:"form-control"%> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status, class:"form-control"%> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload, class:"form-control" %> </br>
    <%= f.submit "Save" , class:"btn btn-success"%>
<% end %>
</div>
</div>
</div>
</div>

app/views/payments/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
    <div class="row">
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> 

</br>
    

        ID Transsaction : <%= @payment.id_transtaction %> </br>
        Status : <%= @payment.status %> </br>
        Upload : <%= @payment.upload %> </br>
    </div>
</div>

<div class="container">
    <div class="row">
        <%= link_to 'Home', payments_path(), class:"btn btn-success" %>
    </div>
</div>

app/views/reports/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
<div class="row">
<div class="col-sm-5">
<%= form_for(@report) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title , class:"form-control"%> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil ,class:"form-control"%> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel, class:"form-control" %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id, class:"form-control" %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id, class:"form-control" %> </br>

    <%= f.label :date %> </br>
    <%= f.text_field :date, class:"form-control" %> </br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/reports/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
<table class="table">
    <tr>
        <th>Titile</th>
        <th>Mapel</th>
        <th>Action</th>
    </tr>
    <% @report.each do |s|%>
    <tr>
        <td><%= s.title %></td>
        <td><%= s.mapel %></td>
        <td><%= link_to 'Detail', report_path(s), class:"btn btn-info" %> <%= link_to 'Edit', edit_report_path(s),class:"btn btn-warning" %>
        <%= link_to 'Delete', s ,class:"btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
</table>

<%= link_to 'New', new_report_path(), class:"btn btn-success" %>

app/views/reports/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
<div class="row">
<div class="col-sm-5">
<%= form_for(@report) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title , class:"form-control"%> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil ,class:"form-control"%> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel, class:"form-control" %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id, class:"form-control" %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id, class:"form-control" %> </br>

    <%= f.label :date %> </br>
    <%= f.text_field :date, class:"form-control" %> </br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/reports/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
<div class="row">
<div class="col-sm-5">
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
Title : <%= @report.title %> </br>
Hasil : <%= @report.hasil %> </br>
Mapel : <%= @report.mapel %> </br>
TeacherId : <%= @report.teacher_id %> </br>
StudentId : <%= @report.student_id %> </br>
Date : <%= @report.date %> </br>
</div>
</div>
<%= link_to 'Home', reports_path(), class:"btn btn-success" %>
</div>

app/views/students/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="countainer">
<div class="row">
<div class="col-sm-5">
<%= form_for(@student) do |f| %>
    <%= f.label :name %> </br>
    <%= f.text_field :name , class:"form-control"%> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username ,class:"form-control"%> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age ,class:"form-control"%> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas,class:"form-control" %> </br>

    <%= f.label :address %> </br>
    <%= f.text_field :address,class:"form-control" %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city,class:"form-control" %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik,class:"form-control" %> </br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/students/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Username</th>
        <th>Action</th>
    </tr>
    <% @student.each do |s|%>
    <tr>
        <td><%= s.name %></td>
        <td><%= s.username %></td>
        <td><%= link_to 'Detail', student_path(s), class:"btn btn-info" %> <%= link_to 'Edit', edit_student_path(s), class:"btn btn-warning" %>
        <%= link_to 'Delete', s , class:"btn btn-danger" ,method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
</table>

<%= link_to 'New Student', new_student_path(), class:"btn btn-success" %>

app/views/students/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="countainer">
<div class="row">
<div class="col-sm-5">
<%= form_for(@student) do |f| %>
    <%= f.label :name %> </br>
    <%= f.text_field :name , class:"form-control"%> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username ,class:"form-control"%> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age ,class:"form-control"%> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas,class:"form-control" %> </br>

    <%= f.label :address %> </br>
    <%= f.text_field :address,class:"form-control" %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city,class:"form-control" %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik,class:"form-control" %> </br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/students/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
Name : <%= @student.name %> </br>
Username : <%= @student.username %> </br>
Age : <%= @student.age %> </br>
Kelas : <%= @student.kelas %> </br>
Address : <%= @student.address %> </br>
City : <%= @student.city %> </br>
NIK : <%= @student.nik %> </br>
<%= link_to 'Home', students_path(), class:"btn btn-success" %>

app/views/teachers/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="form-gruop">
<div class="row">
<div class="col-sm-5">
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik ,class:"form-control" %> </br>

    <%= f.label :name %> </br>
    <%= f.text_field :name ,class:"form-control"%> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age, class:"form-control" %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas ,class:"form-control"%> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel, class:"form-control" %> </br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/teachers/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Mapel</th>
        <th>Action</th>
    </tr>
    <% @teacher.each do |s|%>
    <tr>
        <td><%= s.name %></td>
        <td><%= s.mapel %></td>
        <td><%= link_to 'Detail', teacher_path(s), class:"btn btn-info" %> <%= link_to 'Edit', edit_teacher_path(s), class:"btn btn-warning" %>
        <%= link_to 'Delete', s ,class:"btn btn-danger" ,method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
</table>

<%= link_to 'New Teacher', new_teacher_path() ,class:"btn btn-success"%>

app/views/teachers/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="form-gruop">
<div class="row">
<div class="col-sm-5">
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik ,class:"form-control" %> </br>

    <%= f.label :name %> </br>
    <%= f.text_field :name ,class:"form-control"%> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age, class:"form-control" %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas ,class:"form-control"%> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel, class:"form-control" %> </br>

    <%= f.submit "Save" , class:"btn btn-success"%>
<% end %>
</div>
</div>
</div>

app/views/teachers/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
  <div class="row">
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
NIK : <%= @teacher.nik %> </br>
Name : <%= @teacher.name %> </br>
Age : <%= @teacher.age %> </br>
Kelas : <%= @teacher.kelas %> </br>
Mapel : <%= @teacher.mapel %> </br>
</div>
<div class="row">
<%= link_to 'Home', teachers_path(), class:"btn btn-success" %>
</div>
</div>